/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3ita_poznamky;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import java.time.LocalDateTime;

/**
 *
 * @author Krouzek
 */
public class Window extends javax.swing.JFrame {
    private Poznamkovy_blok blok = new Poznamkovy_blok();
    private ArrayList<JButton> tlacitka = new ArrayList<>();
    private ArrayList<JTextArea> poznamky = new ArrayList<>();
    
    public Window() {
        initComponents();
    }
    
    public void pridejPoznamku(String nadpis, String text){
       blok.pridejPoznamku(new Poznamka(nadpis, LocalDateTime.now().toString(), text));
       pridejBtn.setEnabled(true);
       SmazKomponenty();
       zobrazPoznamky();
    }
    public void zavriPridej(){
        pridejBtn.setEnabled(true);
    }
    public void zobrazPoznamky () 
    {
        this.repaint();
        tlacitka.clear();
        poznamky.clear();
        blok.nactiPoznamky();
        int x = 50;
        int y = 50;
        for (int i = 0; i < blok.getPoznamky().size(); i++) {
            JTextArea area = new JTextArea();
            JButton tlacitko = new JButton("smazat");
            area.setText(blok.getPoznamky().get(i).getCas()+"\n"+blok.getPoznamky().get(i).getNadpis()+"\n"+blok.getPoznamky().get(i).getText());
            area.setSize(200, 100);
            area.setLocation(x, y+i*110); // zmena
            area.setVisible(true);
            area.setLineWrap(true); // zalamovani textu 
            
            tlacitko.setName(Integer.toString(i)); // zmena
            tlacitko.setLocation(x+250, y+20+i*110); //zmena
            tlacitko.setSize(100,50);
            tlacitko.setVisible(true);
            tlacitko.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked (MouseEvent me) 
                {
                    smazPoznamku( Integer.parseInt(me.getComponent().getName()));
                }
            });
            
            poznamky.add(area);
            this.add(area);
            
            tlacitka.add(tlacitko);
            this.add(tlacitko);
            
        }
        
        System.out.println("");
        this.repaint();
        System.out.println("");
    }
    
    public void smazPoznamku (int index) 
    {
        SmazKomponenty();
        blok.smazPoznamku(index);
        zobrazPoznamky();
        this.repaint();        
    }
    
    private void SmazKomponenty(){
        for (int i = 0; i < poznamky.size(); i++) {
            this.remove(poznamky.get(i));
            this.remove(tlacitka.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pridejBtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pridejBtn.setText("Pridej Poznamku");
        pridejBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pridejBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pridejBtn)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pridejBtn)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridejBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pridejBtnMouseClicked
        pridejBtn.setEnabled(false);
        new novaPoznamka(this).setVisible(true);
    }//GEN-LAST:event_pridejBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Window w = new Window();
       w.setSize(500, 500);
       w.setVisible(true);
       w.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       w.zobrazPoznamky();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pridejBtn;
    // End of variables declaration//GEN-END:variables
}
